""" Urls for firestorm app of project ten, for inclusion in LOCAL_PATTERNS.
"""

from django.conf.urls.defaults import patterns, url



urlpatterns = patterns('firestorm.views.views',
    url(r'^join-me/(?P<redirect_string>.*)/$', 'redirect_for_ad_rep',
        name='redirect-for-ad-rep'),
    url(r'^become-a-10coupons-sales-rep/$', 'show_become_an_ad_rep',
        name='become-an-ad-rep'),
    url(r'^become-a-sales-rep/$', 'show_ad_rep_form',
        name='show-ad-rep-form'),
    url(r'^apply-review/$', 'show_apply_review',
        name='show-apply-review'),
    url(r'^enrollment-offer/(?P<payload>.*)/$', 'show_offer_to_enroll', 
        name='show-offer-to-enroll'),
    url(r'^enrollment-offer/$', 'show_offer_to_enroll', 
        name='show-offer-to-enroll'),
    url(r'^benefits-for-business/$', 'redirect_benefits_for_business'),
    url(r'^marketing-resources/benefits-for-business/$',
        'show_benefits_for_business', name='benefits-for-business'),
    url(r'^marketing-resources/benefits-for-business-print/$',
        'show_business_print_benefits', name='benefits-for-business-print'),
    url(r'^marketing-resources/bulletin-board-print/$',
        'show_bulletin_board_print', name='bulletin-board-print'),
    url(r'^compensation-overview/$', 'redirect_compensation_overview'),
    url(r'^marketing-resources/compensation-overview/$',
        'show_compensation_overview', name='compensation-overview'),
    url(r'^our-competition/$', 'redirect_our_competition'),
    url(r'^marketing-resources/our-competition/$',
        'show_our_competition', name='our-competition'),
    url(r'^marketing-resources/our-competition-print/$',
        'show_our_competition_print', name='our-competition-print'),
    url(r'^marketing-resources/simple-steps-print/$',
        'show_simple_steps_print', name='simple-steps-print'),
    url(r'^marketing-resources/testimonial-ad-rep/$',
        'show_testimonial_ad_rep', name='testimonial-ad-rep'),
    url(r'^the-10localcoupons-story/$', 'redirect_10localcoupons_story'),
    url(r'^marketing-resources/the-10localcoupons-story/$',
        'show_the_10localcoupons_story', name='the-10localcoupons-story'),
    url(r'^your-opportunity/$', 'redirect_your_opportunity'),
    url(r'^marketing-resources/your-opportunity/$', 'show_your_opportunity',
        name='your-opportunity'),
    url(r'^compensation-plan/$', 'redirect_compensation_plan'),
    url(r'^marketing-resources/compensation-plan/$', 'show_compensation_plan',
        name='compensation-plan'),
    url(r'^terms-of-agreement/$', 'redirect_terms_of_agreement'),
    url(r'^marketing-resources/terms-of-agreement/$', 'show_terms_of_agreement',
        name='terms-of-agreement'),
    url(r'^policies-procedures/$', 'redirect_policies_procedures'),
    url(r'^marketing-resources/policies-procedures/$',
        'show_policies_procedures', name='policies-procedures'),
    url(r'^build-your-network/$', 'show_ad_rep_menu',
        name='build-your-network'),
    url(r'^virtual-office-password-help/$',
        'show_firestorm_password_help', name='firestorm-password-help'),
    url(r'^virtual-office', 'redirect_virtual_office', 
        name='firestorm-virtual-office'),
    url(r'^ad-rep-business-cards/$', 'show_pdf_business_cards',
        name='ad-rep-business-cards'),
    url(r'^quick-start/(?P<payload>.*)/$', 'show_quick_start_assistance', 
        name='quick-start'),
    url(r'^quick-start/$', 'show_quick_start_assistance', name='quick-start'),
    url(r'^recommend/$', 'show_recommend_enroll', name='recommend-enroll'),
    url(r'^recommend-success/$', 'show_recommend_enroll_success',
        name='recommend-enroll-success'),
    



    url(r'^ad-rep-summary/(?P<ad_rep_id>\d+)/$', 'show_ad_rep_summary',
        name='ad-rep-summary'),
    url(r'^ad-rep-summary/$', 'show_ad_rep_summary', name='ad-rep-summary'),
    # Wildcard url catcher; MUST be last:
    url(r'^(?P<ad_rep_url>[-\w]+)/$', 'ad_rep_home', name='ad-rep-home'),
)
